### PR TITLE
Add newline before EOF when serializing the fixed package.json

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by cameronhunter** [comment]
Great addition, but the snapshots need updated for the tests to pass. Run:

```
$ npm test -- -u
```

**Comment by papandreou** [comment]
@cameronhunter Ah, I didn't realize that. Let's see if that worked :)

**Comment by cameronhunter** [comment]
Thanks for making tide changes. Merged.

**Comment by cameronhunter** [comment]
I'll publish this when I'm at a laptop (I'm currently mobile) and update the thread with the release version. Thanks again.

**Comment by cameronhunter** [comment]
Published as `prettier-package-json@1.4.0`. Thanks for your contribution!

**Pull request merged**
